export enum ErrorCodes {
  LOCATION_NOT_FOUND,
  LOCATION_NO_RESULT,
  LOCATION_ROUTE_TOO_LONG,
  ROUTE_MISSING_PARAMS,
  DB_CANT_SAVE,
  ORDER_NOT_FOUND,
  STRIPE_ERROR,
  MAIL_ERROR,
  GOOGLE_INVALID_REQUEST,
  GOOGLE_OVER_LIMIT,
  GOOGLE_REQUEST_DENIED,
  GOOGLE_UNKNOWN_ERROR,
}
